//! Copy `../../programs` into `$OUT_DIR/embedded_programs_src/` and emit `$OUT_DIR/embedded_programs.rs`
//! with `include_bytes!` for each file. `include_dir!` proc-macros were unreliable for nested dirs here.

use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = manifest.join("../../programs");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let out = Path::new(&out_dir);
    let bundle = out.join("embedded_programs_src");
    println!("cargo:rerun-if-changed={}", src.display());
    println!("cargo:rerun-if-changed=build.rs");
    if !src.is_dir() {
        panic!(
            "expected AINL programs at {} (clone armaraos repo layout)",
            src.display()
        );
    }
    copy_dir_clean(&src, &bundle).expect("copy programs into OUT_DIR");

    let mut rel_paths: Vec<String> = Vec::new();
    collect_files(&bundle, &bundle, &mut rel_paths);
    rel_paths.sort();

    let gen_path = out.join("embedded_programs.rs");
    let mut f = fs::File::create(&gen_path).expect("create embedded_programs.rs");
    writeln!(
        f,
        "// @generated by build.rs — do not edit\n\
         pub static EMBEDDED_AINL_FILES: &[(&str, &[u8])] = &["
    )
    .unwrap();
    for rel in &rel_paths {
        writeln!(
            f,
            "    ({rel:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/embedded_programs_src/{rel}\"))),"
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
}

fn copy_dir_clean(src: &Path, dst: &Path) -> std::io::Result<()> {
    if dst.exists() {
        fs::remove_dir_all(dst)?;
    }
    copy_dir_recursive(src, dst)
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let path = entry.path();
        let name = entry.file_name();
        let out = dst.join(&name);
        if path.is_dir() {
            copy_dir_recursive(&path, &out)?;
        } else {
            fs::copy(&path, &out)?;
        }
    }
    Ok(())
}

fn collect_files(root: &Path, path: &Path, out: &mut Vec<String>) {
    let read = match fs::read_dir(path) {
        Ok(r) => r,
        Err(_) => return,
    };
    for entry in read.flatten() {
        let p = entry.path();
        if p.is_dir() {
            collect_files(root, &p, out);
        } else if p.is_file() {
            let rel = p.strip_prefix(root).unwrap();
            out.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
}
