//! Build automation tasks for the OpenFang workspace.
//!
//! This is the home for "glue" steps that don't belong in crates themselves,
//! especially packaging-time tasks.

use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{anyhow, Context, Result};
use clap::{Parser, Subcommand};
use flate2::read::GzDecoder;
use tar::Archive;

#[derive(Debug, Parser)]
#[command(name = "xtask")]
#[command(about = "Workspace automation tasks", long_about = None)]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Debug, Subcommand)]
enum Cmd {
    /// Download a pinned `ainativelang` wheel into the desktop bundle resources.
    ///
    /// The output location is:
    ///   crates/openfang-desktop/resources/ainl/
    ///
    /// This step is intended to run in the release pipeline before the Tauri bundle.
    BundleAinlWheel {
        /// AINL version to download from PyPI.
        #[arg(long, default_value = "1.4.0")]
        version: String,

        /// If set, remove any existing `ainativelang-*-py3-none-any.whl` before downloading.
        #[arg(long, default_value_t = true)]
        clean: bool,

        /// Extra pip index URL (for private mirrors / caching proxies).
        #[arg(long)]
        extra_index_url: Option<String>,
    },
    /// Download python-build-standalone "install_only" CPython into desktop resources (per Rust target triple).
    ///
    /// Output: `crates/openfang-desktop/resources/python/<triple>/python/...`
    BundlePortablePython {
        /// Rust target triple (e.g. `aarch64-apple-darwin`, `x86_64-pc-windows-msvc`).
        #[arg(long)]
        target: String,
    },
    /// Create `programs/<slug>/` with a starter `.ainl` graph (AINL-first policy).
    ScaffoldAinlProgram {
        /// Human-readable name; slugified for the directory and file (e.g. "Cost alert" → `cost-alert`).
        #[arg(long)]
        name: String,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.cmd {
        Cmd::BundleAinlWheel {
            version,
            clean,
            extra_index_url,
        } => bundle_ainl_wheel(&version, clean, extra_index_url.as_deref()),
        Cmd::BundlePortablePython { target } => bundle_portable_python(&target),
        Cmd::ScaffoldAinlProgram { name } => scaffold_ainl_program(&name),
    }
}

/// Slug for paths: lowercase `a-z0-9` separated by `-`.
fn slugify_program_name(name: &str) -> Result<String> {
    let mut out: Vec<char> = Vec::new();
    let mut prev_sep = false;
    for c in name.trim().chars() {
        let c = if c.is_ascii_alphanumeric() {
            c.to_ascii_lowercase()
        } else if c.is_whitespace() || c == '_' || c == '-' {
            '-'
        } else {
            '-'
        };
        if c == '-' {
            if !out.is_empty() && !prev_sep {
                out.push('-');
            }
            prev_sep = true;
        } else {
            out.push(c);
            prev_sep = false;
        }
    }
    while out.last() == Some(&'-') {
        out.pop();
    }
    let s: String = out.into_iter().collect();
    if s.len() < 2
        || !s
            .chars()
            .next()
            .map(|c| c.is_ascii_alphabetic())
            .unwrap_or(false)
    {
        return Err(anyhow!(
            "Invalid --name {:?}: use at least 2 chars, starting with a letter (e.g. \"My Program\")",
            name.trim()
        ));
    }
    Ok(s)
}

fn graph_identifier(slug: &str) -> String {
    slug.replace('-', "_")
}

fn scaffold_ainl_program(name: &str) -> Result<()> {
    let slug = slugify_program_name(name)?;
    let gid = graph_identifier(&slug);
    let root = repo_root()?;
    let dir = root.join("programs").join(&slug);
    if dir.exists() {
        return Err(anyhow!("Refusing to overwrite existing {:?}", dir));
    }
    std::fs::create_dir_all(&dir).with_context(|| format!("Creating {dir:?}"))?;

    let ainl_path = dir.join(format!("{slug}.ainl"));
    let ainl = format!(
        r#"# {gid} — generated by `cargo run -p xtask -- scaffold-ainl-program --name {}`
# Policy: docs/ainl-first-language.md
# Validate: ainl validate programs/{slug}/{slug}.ainl --strict

{gid}:
  result = core.ADD 0 0
  out result
"#,
        name.trim()
    );
    std::fs::write(&ainl_path, &ainl).with_context(|| format!("Writing {ainl_path:?}"))?;

    let readme_path = dir.join("README.md");
    let readme = format!(
        r#"# {}

Starter AINL graph: [`{slug}.ainl`]({slug}.ainl).

- Policy: [docs/ainl-first-language.md](../../docs/ainl-first-language.md)
- Validate: `ainl validate programs/{slug}/{slug}.ainl --strict`
"#,
        name.trim()
    );
    std::fs::write(&readme_path, readme).with_context(|| format!("Writing {readme_path:?}"))?;

    println!("Created:");
    println!("  {}", ainl_path.display());
    println!("  {}", readme_path.display());
    Ok(())
}

/// indygreg/python-build-standalone release tag + embedded CPython version string.
const PBS_RELEASE: &str = "20241007";
const PBS_PY_VERSION: &str = "3.12.7";

fn bundle_portable_python(rust_target: &str) -> Result<()> {
    let triple = match rust_target.trim() {
        "aarch64-apple-darwin"
        | "x86_64-apple-darwin"
        | "x86_64-unknown-linux-gnu"
        | "aarch64-unknown-linux-gnu"
        | "x86_64-pc-windows-msvc"
        | "aarch64-pc-windows-msvc" => rust_target.trim(),
        other => {
            return Err(anyhow!(
                "unsupported --target {other:?}; use a desktop Rust triple (see `bundle-portable-python --help`)"
            ));
        }
    };

    let url = format!(
        "https://github.com/indygreg/python-build-standalone/releases/download/{PBS_RELEASE}/cpython-{PBS_PY_VERSION}+{PBS_RELEASE}-{triple}-install_only.tar.gz"
    );

    let root = repo_root()?;
    let out_base = root
        .join("crates")
        .join("openfang-desktop")
        .join("resources")
        .join("python")
        .join(triple);

    if out_base.exists() {
        std::fs::remove_dir_all(&out_base).with_context(|| format!("Removing {out_base:?}"))?;
    }
    std::fs::create_dir_all(&out_base).with_context(|| format!("Creating {out_base:?}"))?;

    eprintln!("Downloading portable Python: {url}");
    let resp = ureq::get(&url)
        .call()
        .map_err(|e| anyhow!("GET {url}: {e}"))?;
    let mut body = Vec::new();
    resp.into_reader()
        .read_to_end(&mut body)
        .map_err(|e| anyhow!("read response: {e}"))?;

    let mut decoder = GzDecoder::new(&body[..]);
    let mut archive = Archive::new(&mut decoder);
    archive
        .unpack(&out_base)
        .with_context(|| format!("Unpacking archive into {out_base:?}"))?;

    let unix_py = out_base.join("python").join("bin").join("python3");
    let win_py = out_base.join("python").join("python.exe");
    if !unix_py.exists() && !win_py.exists() {
        return Err(anyhow!(
            "After extract, expected python at {:?} or {:?}",
            unix_py,
            win_py
        ));
    }

    println!("Portable Python ({triple}) -> {}", out_base.display());
    Ok(())
}

fn repo_root() -> Result<PathBuf> {
    // Works in CI and locally as long as invoked somewhere inside the repo.
    let out = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .context("Running git rev-parse to detect repo root")?;
    if !out.status.success() {
        return Err(anyhow!(
            "git rev-parse failed (exit={})",
            out.status.code().unwrap_or(-1)
        ));
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() {
        return Err(anyhow!("git rev-parse returned empty repo root"));
    }
    Ok(PathBuf::from(s))
}

fn run(cmd: &mut Command) -> Result<()> {
    let out = cmd.output().with_context(|| format!("Running {cmd:?}"))?;
    if out.status.success() {
        return Ok(());
    }
    Err(anyhow!(
        "Command failed (exit={})\nstdout:\n{}\nstderr:\n{}",
        out.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    ))
}

fn remove_existing_wheels(dir: &Path) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for ent in std::fs::read_dir(dir).with_context(|| format!("Reading {dir:?}"))? {
        let ent = ent?;
        let p = ent.path();
        let name = p.file_name().and_then(|s| s.to_str()).unwrap_or("");
        if name.starts_with("ainativelang-") && name.ends_with(".whl") {
            std::fs::remove_file(&p).with_context(|| format!("Removing existing wheel {p:?}"))?;
        }
    }
    Ok(())
}

fn bundle_ainl_wheel(version: &str, clean: bool, extra_index_url: Option<&str>) -> Result<()> {
    let root = repo_root()?;
    let out_dir = root
        .join("crates")
        .join("openfang-desktop")
        .join("resources")
        .join("ainl");
    std::fs::create_dir_all(&out_dir)
        .with_context(|| format!("Creating resources dir {out_dir:?}"))?;

    if clean {
        remove_existing_wheels(&out_dir)?;
    }

    // Use pip to download a pure-Python wheel that we can install offline later.
    // We keep this small: just the `ainativelang` wheel itself (no dependencies).
    let mut args = vec![
        "-m",
        "pip",
        "download",
        "--only-binary",
        ":all:",
        "--no-deps",
        "--dest",
    ];
    let out_dir_str = out_dir
        .to_str()
        .ok_or_else(|| anyhow!("Non-utf8 output dir path: {out_dir:?}"))?;
    args.push(out_dir_str);

    // Pin exact version.
    let spec = format!("ainativelang=={version}");
    args.push(&spec);

    if let Some(url) = extra_index_url {
        args.push("--extra-index-url");
        args.push(url);
    }

    // Try python3 first, then python (Windows runners).
    let mut cmd = Command::new("python3");
    cmd.args(args.clone());
    if run(&mut cmd).is_err() {
        let mut cmd = Command::new("python");
        cmd.args(args);
        run(&mut cmd)?;
    }

    // Sanity: verify at least one wheel exists after download.
    let mut found = false;
    for ent in std::fs::read_dir(&out_dir).with_context(|| format!("Reading {out_dir:?}"))? {
        let ent = ent?;
        let p = ent.path();
        let name = p.file_name().and_then(|s| s.to_str()).unwrap_or("");
        if name.starts_with("ainativelang-") && name.ends_with(".whl") {
            found = true;
            break;
        }
    }
    if !found {
        return Err(anyhow!(
            "No ainativelang wheel found in {out_dir:?} after download"
        ));
    }

    println!("Bundled ainativelang wheel into {}", out_dir.display());
    Ok(())
}
