//! Media understanding engine — image description, audio transcription, video analysis.
//!
//! Auto-cascades through available providers based on configured API keys.

use openfang_types::config::LocalVoiceConfig;
use openfang_types::media::{
    normalize_mime_type, MediaAttachment, MediaConfig, MediaSource, MediaType, MediaUnderstanding,
};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::sync::Semaphore;
use tracing::{info, warn};

/// Media understanding engine.
pub struct MediaEngine {
    config: MediaConfig,
    /// Local whisper.cpp + Piper paths from `[local_voice]` (optional).
    local_voice: LocalVoiceConfig,
    semaphore: Arc<Semaphore>,
}

impl MediaEngine {
    pub fn new(config: MediaConfig, local_voice: LocalVoiceConfig) -> Self {
        let max = config.max_concurrency.clamp(1, 8);
        Self {
            config,
            local_voice,
            semaphore: Arc::new(Semaphore::new(max)),
        }
    }

    /// Describe an image using a vision-capable LLM.
    /// Auto-cascade: Anthropic -> OpenAI -> Gemini (based on API key availability).
    pub async fn describe_image(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Image {
            return Err("Expected image attachment".into());
        }

        // Determine which provider to use
        let provider = self.config.image_provider.as_deref()
            .or_else(|| detect_vision_provider())
            .ok_or("No vision-capable LLM provider configured. Set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GEMINI_API_KEY")?;

        // For now, return a structured result indicating the provider.
        // Actual API call would go here using reqwest.
        Ok(MediaUnderstanding {
            media_type: MediaType::Image,
            description: format!(
                "[Image description would be generated by {} provider]",
                provider
            ),
            provider: provider.to_string(),
            model: default_vision_model(provider).to_string(),
        })
    }

    /// Transcribe audio using speech-to-text.
    /// Auto-cascade: Groq (whisper-large-v3-turbo) -> OpenAI (whisper-1).
    pub async fn transcribe_audio(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Audio {
            return Err("Expected audio attachment".into());
        }

        let provider = self.resolve_audio_provider()?;

        let _permit = self.semaphore.acquire().await.map_err(|e| e.to_string())?;

        if provider == "whisper-local" {
            return transcribe_whisper_local(attachment, &self.local_voice).await;
        }

        // Parakeet MLX — local transcription via uv + Python
        if provider == "parakeet-mlx" {
            return transcribe_with_parakeet_mlx(attachment).await;
        }

        // Derive a proper filename with extension from mime_type
        // (Whisper APIs require an extension to detect format)
        let mt = normalize_mime_type(&attachment.mime_type);
        let ext = match mt.as_str() {
            "audio/wav" => "wav",
            "audio/mpeg" | "audio/mp3" => "mp3",
            "audio/ogg" => "ogg",
            "audio/webm" => "webm",
            "audio/mp4" | "audio/m4a" => "m4a",
            "audio/flac" => "flac",
            _ => "wav",
        };

        // Read audio bytes from source
        let audio_bytes = match &attachment.source {
            MediaSource::FilePath { path } => tokio::fs::read(path)
                .await
                .map_err(|e| format!("Failed to read audio file '{}': {}", path, e))?,
            MediaSource::Base64 { data, .. } => {
                use base64::Engine;
                base64::engine::general_purpose::STANDARD
                    .decode(data)
                    .map_err(|e| format!("Failed to decode base64 audio: {}", e))?
            }
            MediaSource::Url { url } => {
                return Err(format!(
                    "URL-based audio source not supported for transcription: {}",
                    url
                ));
            }
        };
        let filename = format!("audio.{}", ext);

        let model = default_audio_model(&provider);

        // Build API request
        let (api_url, api_key) = match provider.as_str() {
            "groq" => (
                "https://api.groq.com/openai/v1/audio/transcriptions",
                std::env::var("GROQ_API_KEY").map_err(|_| "GROQ_API_KEY not set")?,
            ),
            "openai" => (
                "https://api.openai.com/v1/audio/transcriptions",
                std::env::var("OPENAI_API_KEY").map_err(|_| "OPENAI_API_KEY not set")?,
            ),
            other => return Err(format!("Unsupported audio provider: {}", other)),
        };

        info!(provider, model, filename = %filename, size = audio_bytes.len(), "Sending audio for transcription");

        let file_part = reqwest::multipart::Part::bytes(audio_bytes)
            .file_name(filename)
            .mime_str(mt.as_str())
            .map_err(|e| format!("Failed to set MIME type: {}", e))?;

        let form = reqwest::multipart::Form::new()
            .part("file", file_part)
            .text("model", model.to_string())
            .text("response_format", "text");

        let client = reqwest::Client::new();
        let resp = client
            .post(api_url)
            .bearer_auth(&api_key)
            .multipart(form)
            .timeout(std::time::Duration::from_secs(60))
            .send()
            .await
            .map_err(|e| format!("Transcription request failed: {}", e))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(format!("Transcription API error ({}): {}", status, body));
        }

        let transcription = resp
            .text()
            .await
            .map_err(|e| format!("Failed to read transcription response: {}", e))?;

        let transcription = transcription.trim().to_string();
        if transcription.is_empty() {
            return Err("Transcription returned empty text".into());
        }

        info!(
            provider,
            model,
            chars = transcription.len(),
            "Audio transcription complete"
        );

        Ok(MediaUnderstanding {
            media_type: MediaType::Audio,
            description: transcription,
            provider: provider.clone(),
            model: model.to_string(),
        })
    }

    /// Describe video using Gemini.
    pub async fn describe_video(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Video {
            return Err("Expected video attachment".into());
        }

        if !self.config.video_description {
            return Err("Video description is disabled in configuration".into());
        }

        if std::env::var("GEMINI_API_KEY").is_err() && std::env::var("GOOGLE_API_KEY").is_err() {
            return Err("Video description requires GEMINI_API_KEY or GOOGLE_API_KEY".into());
        }

        Ok(MediaUnderstanding {
            media_type: MediaType::Video,
            description: "[Video description would be generated by Gemini]".to_string(),
            provider: "gemini".to_string(),
            model: "gemini-2.5-flash".to_string(),
        })
    }

    /// Resolve STT backend: explicit `[media] audio_provider`, else `[local_voice]` Whisper, else env keys.
    fn resolve_audio_provider(&self) -> Result<String, String> {
        if let Some(ref p) = self.config.audio_provider {
            match p.as_str() {
                "whisper-local" => {
                    if self.local_voice.whisper_ready() {
                        Ok("whisper-local".into())
                    } else {
                        Err(
                            "media.audio_provider is 'whisper-local' but [local_voice] whisper_cli/whisper_model are missing or not files."
                                .into(),
                        )
                    }
                }
                "parakeet-mlx" => Ok("parakeet-mlx".into()),
                "groq" => Ok("groq".into()),
                "openai" => Ok("openai".into()),
                other => Err(format!(
                    "Unknown media.audio_provider: {other}. Use whisper-local, parakeet-mlx, groq, or openai."
                )),
            }
        } else if self.local_voice.whisper_ready() {
            Ok("whisper-local".into())
        } else if std::env::var("OPENFANG_ENABLE_PARAKEET_MLX").is_ok() {
            Ok("parakeet-mlx".into())
        } else if std::env::var("GROQ_API_KEY").is_ok() {
            Ok("groq".into())
        } else if std::env::var("OPENAI_API_KEY").is_ok() {
            Ok("openai".into())
        } else {
            Err(
                "No audio transcription provider. Local STT: ensure whisper-cli is installed (e.g. `brew install whisper-cpp` on macOS) — the daemon auto-downloads ggml-base.bin to ~/.armaraos/voice/models/ on first run. Or set GROQ_API_KEY / OPENAI_API_KEY, or OPENFANG_ENABLE_PARAKEET_MLX.".into(),
            )
        }
    }

    /// Process multiple attachments concurrently (bounded by max_concurrency).
    pub async fn process_attachments(
        &self,
        attachments: Vec<MediaAttachment>,
    ) -> Vec<Result<MediaUnderstanding, String>> {
        let mut handles = Vec::new();

        for attachment in attachments {
            let sem = self.semaphore.clone();
            let config = self.config.clone();
            let local_voice = self.local_voice.clone();
            let handle = tokio::spawn(async move {
                let _permit = sem.acquire().await.map_err(|e| e.to_string())?;
                let engine = MediaEngine {
                    config,
                    local_voice,
                    semaphore: Arc::new(Semaphore::new(1)), // inner engine, no extra semaphore
                };
                match attachment.media_type {
                    MediaType::Image => engine.describe_image(&attachment).await,
                    MediaType::Audio => engine.transcribe_audio(&attachment).await,
                    MediaType::Video => engine.describe_video(&attachment).await,
                }
            });
            handles.push(handle);
        }

        let mut results = Vec::new();
        for handle in handles {
            match handle.await {
                Ok(result) => results.push(result),
                Err(e) => results.push(Err(format!("Task failed: {e}"))),
            }
        }
        results
    }
}

/// Detect which vision provider is available based on environment variables.
fn detect_vision_provider() -> Option<&'static str> {
    if std::env::var("ANTHROPIC_API_KEY").is_ok() {
        return Some("anthropic");
    }
    if std::env::var("OPENAI_API_KEY").is_ok() {
        return Some("openai");
    }
    if std::env::var("GEMINI_API_KEY").is_ok() || std::env::var("GOOGLE_API_KEY").is_ok() {
        return Some("gemini");
    }
    None
}

/// Transcribe audio using Parakeet MLX (local, via uv + Python).
async fn transcribe_with_parakeet_mlx(
    attachment: &MediaAttachment,
) -> Result<MediaUnderstanding, String> {
    use tokio::time::{timeout, Duration};

    // Materialize audio to a temp file if needed
    let (audio_path, is_temp) = match &attachment.source {
        MediaSource::FilePath { path } => (std::path::PathBuf::from(path), false),
        MediaSource::Base64 { data, mime_type } => {
            use base64::Engine;
            let decoded = base64::engine::general_purpose::STANDARD
                .decode(data)
                .map_err(|e| format!("Failed to decode base64 audio: {e}"))?;
            let mt = normalize_mime_type(mime_type);
            let ext = match mt.as_str() {
                "audio/wav" | "audio/x-wav" => "wav",
                "audio/mpeg" | "audio/mp3" => "mp3",
                "audio/ogg" => "ogg",
                "audio/webm" => "webm",
                "audio/mp4" | "audio/m4a" => "m4a",
                "audio/flac" => "flac",
                _ => "wav",
            };
            let path = std::env::temp_dir().join(format!(
                "openfang_parakeet_{}.{}",
                uuid::Uuid::new_v4(),
                ext
            ));
            tokio::fs::write(&path, decoded)
                .await
                .map_err(|e| format!("Failed to write temp audio: {e}"))?;
            (path, true)
        }
        MediaSource::Url { url } => {
            return Err(format!("URL audio not supported for parakeet-mlx: {url}"));
        }
    };

    let script = r#"
import json, sys
from parakeet_mlx import from_pretrained
model = from_pretrained("mlx-community/parakeet-tdt-0.6b-v3")
result = model.transcribe(sys.argv[1])
print(json.dumps({"text": result.text, "model": "mlx-community/parakeet-tdt-0.6b-v3"}))
"#;

    let mut cmd = tokio::process::Command::new("uv");
    cmd.args([
        "run",
        "--with",
        "parakeet-mlx",
        "python3",
        "-c",
        script,
        &audio_path.to_string_lossy(),
    ]);
    cmd.env("PYTHONUNBUFFERED", "1");
    cmd.kill_on_drop(true);

    let output = timeout(Duration::from_secs(900), cmd.output())
        .await
        .map_err(|_| "parakeet-mlx timed out after 15 minutes".to_string())?
        .map_err(|e| format!("Failed to launch parakeet-mlx: {e}"))?;

    if is_temp {
        let _ = tokio::fs::remove_file(&audio_path).await;
    }

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("parakeet-mlx failed: {}", stderr.trim()));
    }

    let stdout =
        String::from_utf8(output.stdout).map_err(|e| format!("parakeet-mlx non-UTF8: {e}"))?;
    let parsed: serde_json::Value = serde_json::from_str(stdout.trim())
        .map_err(|e| format!("parakeet-mlx parse failed: {e}"))?;

    let text = parsed["text"]
        .as_str()
        .ok_or("missing text field")?
        .trim()
        .to_string();
    if text.is_empty() {
        return Err("parakeet-mlx returned empty transcription".into());
    }

    Ok(MediaUnderstanding {
        media_type: MediaType::Audio,
        description: text,
        provider: "parakeet-mlx".to_string(),
        model: parsed["model"]
            .as_str()
            .unwrap_or("parakeet-tdt-0.6b-v3")
            .to_string(),
    })
}

/// whisper.cpp (Homebrew build) documents: flac, mp3, ogg, wav — not webm/m4a.
fn whisper_cli_supported_extension(ext: &str) -> bool {
    matches!(
        ext.to_lowercase().as_str(),
        "wav" | "flac" | "mp3" | "ogg"
    )
}

fn resolve_ffmpeg() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("FFMPEG_PATH").or_else(|_| std::env::var("FFMPEG_BINARY")) {
        let pb = PathBuf::from(p.trim());
        if pb.is_file() {
            return Some(pb);
        }
    }
    // Homebrew default symlink and Cellar layout (when `brew` is not on daemon PATH).
    for p in [
        "/opt/homebrew/bin/ffmpeg",
        "/opt/homebrew/opt/ffmpeg/bin/ffmpeg",
        "/usr/local/bin/ffmpeg",
        "/usr/local/opt/ffmpeg/bin/ffmpeg",
    ] {
        let pb = PathBuf::from(p);
        if pb.is_file() {
            return Some(pb);
        }
    }
    let out = std::process::Command::new("sh")
        .arg("-lc")
        .arg("command -v ffmpeg 2>/dev/null || true")
        .output()
        .ok()?;
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() {
        return None;
    }
    let p = PathBuf::from(s);
    if p.is_file() {
        Some(p)
    } else {
        None
    }
}

/// Convert arbitrary browser/container audio to 16 kHz mono WAV for whisper-cli.
async fn transcode_audio_to_wav_for_whisper(
    ffmpeg: &Path,
    input: &Path,
) -> Result<PathBuf, String> {
    let id = uuid::Uuid::new_v4();
    let out = std::env::temp_dir().join(format!("openfang_wsp_{id}_whisper.wav"));
    let st = tokio::process::Command::new(ffmpeg)
        .arg("-hide_banner")
        .arg("-loglevel")
        .arg("error")
        .args(["-y", "-i"])
        .arg(input)
        .args([
            "-ac",
            "1",
            "-ar",
            "16000",
            "-c:a",
            "pcm_s16le",
            "-f",
            "wav",
        ])
        .arg(&out)
        .status()
        .await
        .map_err(|e| format!("ffmpeg: {e}"))?;
    if !st.success() {
        let _ = tokio::fs::remove_file(&out).await;
        return Err(format!(
            "ffmpeg transcoding failed (status {}). Install ffmpeg (e.g. `brew install ffmpeg`) or use cloud STT.",
            st
        ));
    }
    if !out.is_file() {
        return Err("ffmpeg produced no output file".into());
    }
    Ok(out)
}

/// Local whisper.cpp transcription (`[local_voice]` + ggml-base.bin recommended).
async fn transcribe_whisper_local(
    attachment: &MediaAttachment,
    lv: &LocalVoiceConfig,
) -> Result<MediaUnderstanding, String> {
    let cli = lv
        .whisper_cli
        .as_ref()
        .ok_or_else(|| "whisper_cli path missing".to_string())?;
    let model = lv
        .whisper_model
        .as_ref()
        .ok_or_else(|| "whisper_model path missing".to_string())?;

    let mt = normalize_mime_type(&attachment.mime_type);
    let ext = match mt.as_str() {
        "audio/wav" | "audio/x-wav" => "wav",
        "audio/mpeg" | "audio/mp3" => "mp3",
        "audio/ogg" => "ogg",
        "audio/webm" => "webm",
        "audio/mp4" | "audio/m4a" => "m4a",
        "audio/flac" => "flac",
        _ => "webm",
    };
    let id = uuid::Uuid::new_v4();
    let tmp: PathBuf = std::env::temp_dir().join(format!("openfang_wsp_{id}.{ext}"));

    let audio_bytes = match &attachment.source {
        MediaSource::FilePath { path } => tokio::fs::read(path)
            .await
            .map_err(|e| format!("read audio: {e}"))?,
        MediaSource::Base64 { data, .. } => {
            use base64::Engine;
            base64::engine::general_purpose::STANDARD
                .decode(data)
                .map_err(|e| format!("decode: {e}"))?
        }
        MediaSource::Url { url } => {
            return Err(format!("URL audio not supported for whisper-local: {url}"));
        }
    };
    tokio::fs::write(&tmp, &audio_bytes)
        .await
        .map_err(|e| format!("temp audio: {e}"))?;

    // Browser voice messages are typically WebM; whisper-cli only accepts flac/mp3/ogg/wav.
    let mut whisper_input = tmp.clone();
    let mut transcoded: Option<PathBuf> = None;
    if !whisper_cli_supported_extension(ext) {
        let Some(ffmpeg) = resolve_ffmpeg() else {
            let _ = tokio::fs::remove_file(&tmp).await;
            return Err(
                "Local whisper-cli does not decode WebM/M4A directly. Install ffmpeg (e.g. `/opt/homebrew/bin/brew install ffmpeg` on Apple Silicon) or set FFMPEG_PATH to the binary. Cloud: GROQ_API_KEY / OPENAI_API_KEY."
                    .into(),
            );
        };
        info!(
            ext = %ext,
            "transcoding audio for whisper-local via ffmpeg (whisper-cli accepts flac/mp3/ogg/wav only)"
        );
        match transcode_audio_to_wav_for_whisper(&ffmpeg, &tmp).await {
            Ok(wav) => {
                transcoded = Some(wav.clone());
                whisper_input = wav;
            }
            Err(e) => {
                let _ = tokio::fs::remove_file(&tmp).await;
                return Err(e);
            }
        }
    }

    let out = tokio::process::Command::new(cli)
        .arg("-m")
        .arg(model.as_os_str())
        .arg("-f")
        .arg(whisper_input.as_os_str())
        .arg("-nt")
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .await
        .map_err(|e| format!("whisper-cli: {e}"))?;

    let sidecar: PathBuf = format!("{}.txt", whisper_input.display()).into();
    let mut text = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if text.is_empty() {
        if let Ok(s) = tokio::fs::read_to_string(&sidecar).await {
            text = s.trim().to_string();
            let _ = tokio::fs::remove_file(&sidecar).await;
        }
    }
    if text.is_empty() {
        let j = whisper_input.with_extension("json");
        if let Ok(s) = tokio::fs::read_to_string(&j).await {
            if let Ok(v) = serde_json::from_str::<serde_json::Value>(&s) {
                if let Some(t) = v["transcription"].as_str().or_else(|| v["text"].as_str()) {
                    text = t.trim().to_string();
                }
            }
            let _ = tokio::fs::remove_file(&j).await;
        }
    }
    if text.is_empty() && out.stderr.len() > 200 {
        warn!(
            stderr = %String::from_utf8_lossy(&out.stderr).chars().take(2000).collect::<String>(),
            "whisper-cli: empty transcript; stderr excerpt may indicate decode issues"
        );
    }

    let _ = tokio::fs::remove_file(&tmp).await;
    if let Some(ref p) = transcoded {
        let _ = tokio::fs::remove_file(p).await;
    }

    if text.is_empty() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        return Err(format!(
            "whisper-local returned no text (status {}). stderr: {}",
            out.status,
            stderr.trim()
        ));
    }

    let model_label = model
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("whisper-local")
        .to_string();
    Ok(MediaUnderstanding {
        media_type: MediaType::Audio,
        description: text,
        provider: "whisper-local".to_string(),
        model: model_label,
    })
}

/// Get the default vision model for a provider.
fn default_vision_model(provider: &str) -> &str {
    match provider {
        "anthropic" => "claude-sonnet-4-20250514",
        "openai" => "gpt-4o",
        "gemini" => "gemini-2.5-flash",
        _ => "unknown",
    }
}

/// Get the default audio model for a provider.
fn default_audio_model(provider: &str) -> &str {
    match provider {
        "whisper-local" => "whisper-cpp-local",
        "parakeet-mlx" => "mlx-community/parakeet-tdt-0.6b-v3",
        "groq" => "whisper-large-v3-turbo",
        "openai" => "whisper-1",
        _ => "unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use openfang_types::config::LocalVoiceConfig;
    use openfang_types::media::{MediaSource, MAX_IMAGE_BYTES};

    #[test]
    fn test_engine_creation() {
        let config = MediaConfig::default();
        let engine = MediaEngine::new(config, LocalVoiceConfig::default());
        assert_eq!(engine.config.max_concurrency, 2);
    }

    #[test]
    fn test_engine_max_concurrency_clamped() {
        let config = MediaConfig {
            max_concurrency: 100,
            ..Default::default()
        };
        let engine = MediaEngine::new(config, LocalVoiceConfig::default());
        // Semaphore was clamped to 8
        assert!(engine.semaphore.available_permits() <= 8);
    }

    #[tokio::test]
    async fn test_describe_image_wrong_type() {
        let engine = MediaEngine::new(MediaConfig::default(), LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/mpeg".into(),
            source: MediaSource::FilePath {
                path: "test.mp3".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Expected image"));
    }

    #[tokio::test]
    async fn test_describe_image_invalid_mime() {
        let engine = MediaEngine::new(MediaConfig::default(), LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "application/pdf".into(),
            source: MediaSource::FilePath {
                path: "test.pdf".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_describe_image_too_large() {
        let engine = MediaEngine::new(MediaConfig::default(), LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "big.png".into(),
            },
            size_bytes: MAX_IMAGE_BYTES + 1,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_transcribe_audio_wrong_type() {
        let engine = MediaEngine::new(MediaConfig::default(), LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "test.png".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_video_disabled() {
        let config = MediaConfig {
            video_description: false,
            ..Default::default()
        };
        let engine = MediaEngine::new(config, LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Video,
            mime_type: "video/mp4".into(),
            source: MediaSource::FilePath {
                path: "test.mp4".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_video(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("disabled"));
    }

    #[test]
    fn test_detect_vision_provider_none() {
        // In test env, likely no API keys set — should return None.
        // (This test is environment-dependent, but safe.)
        let _ = detect_vision_provider(); // Just verify it doesn't panic
    }

    #[test]
    fn test_default_vision_models() {
        assert_eq!(
            default_vision_model("anthropic"),
            "claude-sonnet-4-20250514"
        );
        assert_eq!(default_vision_model("openai"), "gpt-4o");
        assert_eq!(default_vision_model("gemini"), "gemini-2.5-flash");
        assert_eq!(default_vision_model("unknown"), "unknown");
    }

    #[test]
    fn test_default_audio_models() {
        assert_eq!(default_audio_model("groq"), "whisper-large-v3-turbo");
        assert_eq!(default_audio_model("openai"), "whisper-1");
    }

    #[tokio::test]
    async fn test_transcribe_audio_rejects_image_type() {
        let engine = MediaEngine::new(MediaConfig::default(), LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "test.png".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Expected audio"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_no_provider() {
        // With no API keys set, should fail with provider error
        let engine = MediaEngine::new(MediaConfig::default(), LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::FilePath {
                path: "test.webm".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        // Either fails with "No audio transcription provider" or file read error
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_transcribe_audio_url_source_rejected() {
        // URL source should be rejected
        let config = MediaConfig {
            audio_provider: Some("groq".to_string()),
            ..Default::default()
        };
        let engine = MediaEngine::new(config, LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/mpeg".into(),
            source: MediaSource::Url {
                url: "https://example.com/audio.mp3".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .contains("URL-based audio source not supported"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_file_not_found() {
        let config = MediaConfig {
            audio_provider: Some("groq".to_string()),
            ..Default::default()
        };
        let engine = MediaEngine::new(config, LocalVoiceConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::FilePath {
                path: "/nonexistent/path/audio.webm".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Failed to read audio file"));
    }
}
